/**
 * Contract addresses for the base network.
 * Auto-generated by `scripts/generate-deployment-artifacts.mjs` -- do not edit manually.
 */

export const FORUMS = {
  "global": "0x7D3d1Ea00A9874eFA5a102cd1c534ec9b445032F",
  "USA": "0x16392cD70b9457179223ef655D1db2841631Ddb8",
  "CAN": "0xa0a5353b3760985ECd9a8D01E91416c6065bcd6d"
} as const;

export const REGISTRY_ADDRESS = "0x95e0f4F8898C46a7511241dBEF3b5a0a5933e1d1" as const;
