/**
 * Contract addresses for the base_sepolia network with MockSymvoliaRegistry.
 * Auto-generated by `scripts/generate-deployment-artifacts.mjs` -- do not edit manually.
 */

export const FORUMS = {
  "global": "0x5Ee636f29Ede8c51c5C3BFbCAb7B2cdB5f8F56FE",
  "USA": "0x894576eb90AfE57Fd23951648E4834A4f9354D33",
  "CAN": "0xaAC890075A66FeEA4B48923Da808F79241bb5fe7"
} as const;

export const REGISTRY_ADDRESS = "0x43C515FAF9e28B4bAcD19d3803cf254EF055d317" as const;
