/**
 * Contract addresses for the base_sepolia network with MockSymvoliaRegistry.
 * Auto-generated by `scripts/generate-deployment-artifacts.mjs` -- do not edit manually.
 */

export const FORUMS = {
  "global": "0x399aeE46Dc08DAf9526447F83A364e935DD5e59D",
  "USA": "0xaA500158feF1F6Be6188067BaD6453c2176b8014",
  "CAN": "0x4cd5342fA2463d37358ef57d5ec93B3A678FDA07"
} as const;

export const REGISTRY_ADDRESS = "0x5C1e436De7B28c10f0A58D09f670377B05b9b9CD" as const;
